name: release

on: [workflow_dispatch]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: npm install
        run: npm install --save-dev semantic-release
        #run: npm install semantic-release @semantic-release/git @semantic-release/github -D
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          #AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}