name: release

on: [workflow_dispatch]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # clone a repository
      - name: release
        run: npx semantic-release
        env:
          #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}